### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by JoyceBabu** [CpanelInc/scl-php71#2]
https://github.com/CpanelInc/scl-php71/blob/fc8881ef1c8010709401cfd9fae455fea4c636f3/SOURCES/Makefile#L6

Shouldn't it be 

```
rpmbuild $(RPMDEFINES) $(SRCDEFINES) --define 'scl php71' -bs $(NAME).spec
```

**Comment by drmuey** [comment]
Probably so, thank you! I've created internal case ZC-2827 to resolve this, much appreciated!
